name: Semgrep
on:
  pull_request: {}
  push:
    branches:
      - semgrep2
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          auditOn: push
          publishUrl: https://semgrep.snowflake.com
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
